<?php
/**
 * FetchInboxMessages200ResponseDataTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Mediana\Sdk
 * @author   Mediana Team
 * @link     https://mediana.ir
 */

/**
 * Mediana sms api
 *
 * Mediana sms api doc </br>  sdks for some programming languages is in out github at https://github.com/ippanelippanel </br> api-key format: <code>Authorization: \"AccessKey your-api-key\"</code>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the Project document: 1.0.1
 * Generated by: https://mediana.ir
 * Engine version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by Mediana Team (https://mediana.ir).
 * https://mediana.ir
 * Please update the test case below to test the model.
 */

namespace Mediana\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FetchInboxMessages200ResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description FetchInboxMessages200ResponseData
 * @package     Mediana\Sdk
 * @author      Mediana Team
 * @link        https://mediana.ir
 */
class FetchInboxMessages200ResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FetchInboxMessages200ResponseData"
     */
    public function testFetchInboxMessages200ResponseData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "messages"
     */
    public function testPropertyMessages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
